import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import ReactQueryWrapper from "@/components/wrappers/ReactQueryWrapper";
import ReduxProvider from "@/components/wrappers/ReduxProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <ReactQueryWrapper>{children}</ReactQueryWrapper>
        </ReduxProvider>
      </body>
    </html>
  );
}
